package com.threefees.task.domain;

public enum TaskType {
  IMPORT,
  EXPORT,
  DRAFT_INITIALIZE,
  DRAFT_MESSAGE,
  AI_IMAGE_ANALYSIS,
  FORMAL_REPORT,
  HISTORICAL_REPORT_IMPORT,
  REPORT_CORRECTION
}
