"""create core persistence tables

Revision ID: 3f35f0ced3ba
Revises:
Create Date: 2026-07-31 15:41:27.326261
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3f35f0ced3ba"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), nullable=False, comment="用户ID"),
        sa.Column("account", sa.String(length=64), nullable=False, comment="账号"),
        sa.Column("display_name", sa.String(length=64), nullable=False, comment="展示姓名"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="用户状态"),
        sa.Column("identity_provider", sa.String(length=32), nullable=False, comment="身份来源"),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("account", name=op.f("uq_app_user_account")),
        schema="audit",
        comment="系统登录用户",
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("city_id", sa.SmallInteger(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trace_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        schema="audit",
        comment="操作审计日志",
    )
    op.create_index(
        op.f("ix_audit_log_city_id"), "audit_log", ["city_id"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_audit_log_trace_id"), "audit_log", ["trace_id"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False, schema="audit"
    )
    op.create_table(
        "city",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_city")),
        sa.UniqueConstraint("name", name=op.f("uq_city_name")),
        schema="audit",
        comment="江苏13市主数据",
    )
    op.create_index(op.f("ix_city_code"), "city", ["code"], unique=True, schema="audit")
    op.create_table(
        "site",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("city_id", sa.SmallInteger(), nullable=False),
        sa.Column("site_code", sa.String(length=64), nullable=False),
        sa.Column("site_name", sa.String(length=160), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["city_id"], ["audit.city.id"], name=op.f("fk_site_city_id_city")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_site")),
        sa.UniqueConstraint("city_id", "id", name="uq_site_city_id"),
        sa.UniqueConstraint("city_id", "site_code", name="uq_site_city_code"),
        schema="audit",
        comment="城市报账点",
    )
    op.create_index(op.f("ix_site_city_id"), "site", ["city_id"], unique=False, schema="audit")
    op.create_table(
        "audit_task",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("city_id", sa.SmallInteger(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("task_no", sa.String(length=40), nullable=False),
        sa.Column("audit_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id", "site_id"],
            ["audit.site.city_id", "audit.site.id"],
            name="fk_audit_task_city_site",
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["audit.city.id"], name=op.f("fk_audit_task_city_id_city")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["audit.app_user.id"], name=op.f("fk_audit_task_created_by_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_task")),
        sa.UniqueConstraint("city_id", "id", name="uq_audit_task_city_id"),
        sa.UniqueConstraint("city_id", "task_no", name="uq_audit_task_city_no"),
        schema="audit",
        comment="电费稽核任务",
    )
    op.create_index(
        op.f("ix_audit_task_city_id"), "audit_task", ["city_id"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_audit_task_site_id"), "audit_task", ["site_id"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_audit_task_status"), "audit_task", ["status"], unique=False, schema="audit"
    )
    op.create_table(
        "analysis_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("city_id", sa.SmallInteger(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("run_no", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("progress", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("current_node", sa.String(length=64), nullable=False),
        sa.Column("workflow_version", sa.String(length=32), nullable=False),
        sa.Column(
            "material_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "state_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "progress BETWEEN 0 AND 100", name=op.f("ck_analysis_run_progress_range")
        ),
        sa.ForeignKeyConstraint(
            ["city_id", "task_id"],
            ["audit.audit_task.city_id", "audit.audit_task.id"],
            name="fk_analysis_run_city_task",
        ),
        sa.ForeignKeyConstraint(
            ["city_id"], ["audit.city.id"], name=op.f("fk_analysis_run_city_id_city")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["audit.app_user.id"], name=op.f("fk_analysis_run_created_by_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_run")),
        sa.UniqueConstraint("city_id", "id", name="uq_analysis_run_city_id"),
        sa.UniqueConstraint("task_id", "run_no", name="uq_analysis_run_task_no"),
        schema="audit",
        comment="Agent分析运行",
    )
    op.create_index(
        op.f("ix_analysis_run_city_id"), "analysis_run", ["city_id"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_analysis_run_status"), "analysis_run", ["status"], unique=False, schema="audit"
    )
    op.create_index(
        op.f("ix_analysis_run_task_id"), "analysis_run", ["task_id"], unique=False, schema="audit"
    )
    op.create_table(
        "analysis_event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("city_id", sa.SmallInteger(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("sequence_no", sa.Integer(), nullable=False),
        sa.Column("node_name", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id", "run_id"],
            ["audit.analysis_run.city_id", "audit.analysis_run.id"],
            name="fk_analysis_event_city_run",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_event")),
        sa.UniqueConstraint("run_id", "sequence_no", name="uq_analysis_event_run_sequence"),
        schema="audit",
        comment="Agent节点事件",
    )
    op.create_index(
        op.f("ix_analysis_event_city_id"),
        "analysis_event",
        ["city_id"],
        unique=False,
        schema="audit",
    )
    op.create_index(
        op.f("ix_analysis_event_run_id"), "analysis_event", ["run_id"], unique=False, schema="audit"
    )
    # 固定主数据随结构迁移写入，保证所有环境具有完全一致的城市ID。
    city_table = sa.table(
        "city",
        sa.column("id", sa.SmallInteger()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("status", sa.String()),
        schema="audit",
    )
    op.bulk_insert(
        city_table,
        [
            {"id": 1, "code": "nanjing", "name": "南京", "status": "active"},
            {"id": 2, "code": "wuxi", "name": "无锡", "status": "active"},
            {"id": 3, "code": "xuzhou", "name": "徐州", "status": "active"},
            {"id": 4, "code": "changzhou", "name": "常州", "status": "active"},
            {"id": 5, "code": "suzhou", "name": "苏州", "status": "active"},
            {"id": 6, "code": "nantong", "name": "南通", "status": "active"},
            {"id": 7, "code": "lianyungang", "name": "连云港", "status": "active"},
            {"id": 8, "code": "huaian", "name": "淮安", "status": "active"},
            {"id": 9, "code": "yancheng", "name": "盐城", "status": "active"},
            {"id": 10, "code": "yangzhou", "name": "扬州", "status": "active"},
            {"id": 11, "code": "zhenjiang", "name": "镇江", "status": "active"},
            {"id": 12, "code": "taizhou", "name": "泰州", "status": "active"},
            {"id": 13, "code": "suqian", "name": "宿迁", "status": "active"},
        ],
    )
    user_table = sa.table(
        "app_user",
        sa.column("id", sa.UUID()),
        sa.column("account", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("status", sa.String()),
        sa.column("identity_provider", sa.String()),
        schema="audit",
    )
    op.bulk_insert(
        user_table,
        [
            {
                "id": "00000000-0000-0000-0000-000000000001",
                "account": "development-user",
                "display_name": "开发用户",
                "status": "active",
                "identity_provider": "local",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库结构。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_event_run_id"), table_name="analysis_event", schema="audit")
    op.drop_index(op.f("ix_analysis_event_city_id"), table_name="analysis_event", schema="audit")
    op.drop_table("analysis_event", schema="audit")
    op.drop_index(op.f("ix_analysis_run_task_id"), table_name="analysis_run", schema="audit")
    op.drop_index(op.f("ix_analysis_run_status"), table_name="analysis_run", schema="audit")
    op.drop_index(op.f("ix_analysis_run_city_id"), table_name="analysis_run", schema="audit")
    op.drop_table("analysis_run", schema="audit")
    op.drop_index(op.f("ix_audit_task_status"), table_name="audit_task", schema="audit")
    op.drop_index(op.f("ix_audit_task_site_id"), table_name="audit_task", schema="audit")
    op.drop_index(op.f("ix_audit_task_city_id"), table_name="audit_task", schema="audit")
    op.drop_table("audit_task", schema="audit")
    op.drop_index(op.f("ix_site_city_id"), table_name="site", schema="audit")
    op.drop_table("site", schema="audit")
    op.drop_index(op.f("ix_city_code"), table_name="city", schema="audit")
    op.drop_table("city", schema="audit")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log", schema="audit")
    op.drop_index(op.f("ix_audit_log_trace_id"), table_name="audit_log", schema="audit")
    op.drop_index(op.f("ix_audit_log_city_id"), table_name="audit_log", schema="audit")
    op.drop_table("audit_log", schema="audit")
    op.drop_table("app_user", schema="audit")
    # ### end Alembic commands ###
